// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvFZScUBKO1TC7nGbQ5vX1xKEgX3XDrBM',
    appId: '1:809766324470:web:14a3da595a2a16e76944d7',
    messagingSenderId: '809766324470',
    projectId: 'quiz4-25eda',
    authDomain: 'quiz4-25eda.firebaseapp.com',
    storageBucket: 'quiz4-25eda.appspot.com',
    measurementId: 'G-Q9M3NRX1RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYX1xq0FKDPZYn-BYhikAu8HiKIEyiwI0',
    appId: '1:809766324470:android:95800f3f5c496b106944d7',
    messagingSenderId: '809766324470',
    projectId: 'quiz4-25eda',
    storageBucket: 'quiz4-25eda.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvFZScUBKO1TC7nGbQ5vX1xKEgX3XDrBM',
    appId: '1:809766324470:web:af508821f27988836944d7',
    messagingSenderId: '809766324470',
    projectId: 'quiz4-25eda',
    authDomain: 'quiz4-25eda.firebaseapp.com',
    storageBucket: 'quiz4-25eda.appspot.com',
    measurementId: 'G-2ZLVF77BQW',
  );
}
